import base64
import json
import pickle  # nosec: B301,B403
from typing import Any, Union

from tortoise.indexes import Index


class JsonEncoder(json.JSONEncoder):
    def default(self, obj) -> Any:
        if isinstance(obj, Index):
            if hasattr(obj, "describe"):
                # For tortoise>=0.24
                return obj.describe()
            return {
                "type": "index",
                "val": base64.b64encode(pickle.dumps(obj)).decode(),  # nosec: B301
            }
        else:
            return super().default(obj)


def load_index(obj: dict) -> Index:
    """Convert a dict that generated by `Index.decribe()` to a Index instance"""
    index = Index(fields=obj["fields"] or obj["expressions"], name=obj.get("name"))
    if extra := obj.get("extra"):
        index.extra = extra
    if idx_type := obj.get("type"):
        index.INDEX_TYPE = idx_type
    return index


def object_hook(obj) -> Any:
    if "fields" in obj and not ({"expressions", "name", "type", "extra"} - obj.keys()):
        # Index object of tortoise.__version__ >= '0.24'
        return load_index(obj)
    _type = obj.get("type")
    if not _type:
        return obj
    return pickle.loads(base64.b64decode(obj["val"]))  # nosec: B301


def encoder(obj: dict) -> str:
    return json.dumps(obj, cls=JsonEncoder)


def decoder(obj: Union[str, bytes]) -> Any:
    return json.loads(obj, object_hook=object_hook)
